site_name: Foresight2020
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Blog:
    - Security plus Cert:
        - CIS Overview: blog/Security_Cert/CIS_Overview.md
        - Useful Linux Commands: 'blog/Security_Cert/Useful Linux Commands.md'
        - Study Progress: blog/Security_Cert/Study_progress.md
        - Foundational Concepts: 'blog/Security_Cert/Foundational Concepts.md'